name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Create a temporary file with the environment variables
          echo "const supabaseUrl = '$SUPABASE_URL';" > temp.js
          echo "const supabaseKey = '$SUPABASE_ANON_KEY';" >> temp.js
          
          # Replace the Supabase initialization in the HTML file
          awk '
            /const supabaseUrl =/ { print "const supabaseUrl = \"'"$SUPABASE_URL"'\";"; next }
            /const supabaseKey =/ { print "const supabaseKey = \"'"$SUPABASE_ANON_KEY"'\";"; next }
            { print }
          ' wb/tsstats/index.html > temp.html
          
          # Replace the original file with the modified one
          mv temp.html wb/tsstats/index.html
          rm temp.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: . 