name: script

on:
  #schedule:
  #  - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-player-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm

    # Step 4: Run the Python script
    - name: Run the data collection script
      run: |
        python script.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, if interacting with GitHub API

    # Step 5: Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/wbuserdata.csv
        git commit -m "Daily update: Player data for $(date +'%Y-%m-%d')"
        git push
