name: wbtsdb v2

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12 AM daily
  workflow_dispatch:


jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm

    - name: Run data fetch script
      run: python wbtsdb_v2.py

    - name: Split CSV into chunks
      id: split_csv
      run: |
        # Split the CSV into chunks of approximately 95MB each
        split -b 95M data/wbuserdata_ts.csv data/wbuserdata_ts_part_

    - name: Append and commit chunks
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

        # Append each chunk to the existing CSV file and commit
        for part in data/wbuserdata_ts_part_*
        do
          cat $part >> data/wbuserdata_ts.csv
          git add data/wbuserdata_ts.csv
          git commit -m "Append chunk $part to wbuserdata_ts.csv"
          git push
        done
